site_name: XWR
repo_url: https://github.com/WiseLabCMU/xwr
repo_name: WiseLabCMU/xwr
nav:
  - Home: index.md
  - Setup: setup.md
  - High Level API: system.md
  - Radar Processing:
    - RSP: rsp/rsp.md
    - Pytorch: rsp/torch.md
    - Jax: rsp/jax.md
  - Capture Card:
    - API: dca/api.md
    - Defines: dca/defines.md
    - Types: dca/types.md
  - Radar:
    - API: radar/api.md
    - Defines: radar/defines.md
    - Commands: radar/raw.md

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  icon:
    logo: material/antenna
    annotation: material/arrow-right-circle
  font:
    code: monospace
  features:
    - navigation.instant
    - navigation.expand
  palette:
    primary: blue
    accent: deep purple

plugins:
- search
- autorefs
- mkdocstrings:
    default_handler: python_xref
    handlers:
      python_xref:
        options:
          docstring_style: google
          relative_crossrefs: true
          separate_signature: true
          line_length: 80
          show_signature_annotations: true
          signature_crossrefs: true
          show_root_full_path: true
          show_root_members_full_path: true
          show_symbol_type_heading: true
          show_root_heading: true
          show_root_toc_entry: true
          heading_level: 1
          check_crossrefs_exclude:
          - "^torch\\.(.*)"
          - "^numpy\\.(.*)"
        inventories:
        - https://docs.python.org/3/objects.inv
        - https://numpy.org/doc/stable/objects.inv
        - https://wiselabcmu.github.io/abstract-dataloader/objects.inv
        - https://docs.pytorch.org/docs/stable/objects.inv
        - https://docs.jax.dev/en/latest/objects.inv

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - def_list
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - footnotes
