name: CI

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install uv with Python 3.12
      uses: astral-sh/setup-uv@v6
      with:
        python-version: "3.12"
        uv-version: latest

    - name: Lint with ruff
      run: |
        uv run --extra dev ruff check

    - name: Type check with pyright
      run: |
        uv run --extra dev pyright

    - name: Run tests
      run: |
        uv run --extra dev pytest -ra -- tests
